### ISSUE TITLE
How to get rid of the loading indicator when sending an image.

### ISSUE THREAD

**Issue by StefanGhiban** [antoine92190/vue-advanced-chat#279]
## Describe the bug

When I send an image, the loading indicator doesnt dissapear, compared to a pdf which instantly uploads. One other question would be if I can hide the view buttons for the images, and only keep the download button that opens that image on another page. If I open the image on the current window, it doesnt show up correctly as I have other elements on the page and the styles object of the component isnt really that customizable.

## Screenshots

![image](https://user-images.githubusercontent.com/47953165/151502242-0472087a-fead-44e8-975e-f4cbacc7a4a5.png)
![image](https://user-images.githubusercontent.com/47953165/151502281-a266fe13-63f0-4959-b556-a93b777783d9.png)

## Additional context

I am using nuxt and tailwind css.

**Comment by antoine92190** [comment]
- The image loading indicator should disappear once the image url is coming from a server and not locally.
If the image url contains `blob:http`, then the image will keep loading.

- You should be able to customize the position of the media preview popover with CSS only. Otherwise you can disable this behaviour using `media-preview-enabled` prop. You can also hide the view button using CSS:
```
.vac-button-download {
	display: none;
}
```

**Comment by StefanGhiban** [comment]
Thanks for the help! It worked. Great library btw.

**Comment by antoine92190** [comment]
You can probably use show-footer prop for that
